openapi: 3.0.3
info:
  title: notes-app-API
  description: API for notes-app, a note-taking application with user authentication and note management.
  version: 1.0.0
  contact:
    name: API Support
    email: support@notes-app.com
servers:
  - url: http://localhost:3000
    description: Local development server
tags:
  - name: Authentication
    description: Endpoints for user registration and login
  - name: Notes
    description: Endpoints for creating, retrieving, and managing notes
components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: acces_token
  schemas:
    RegisterResponse:
      type: object
      properties:
        username:
          type: string
          example: johndoe
        message:
          type: string
          example: User successfully registered. Token stored in cookies.

    RegisterRequest:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          example: johndoe
        email:
          type: string
          format: email
          example: johndoe@example.com
        password:
          type: string
          format: password
          example: StrongPass123!

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: johndoe@example.com
        password:
          type: string
          format: password
          example: StrongPass123!
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: An error occurred
          
    LinkRequest:
      type: object
      required:
        - originalUrl
      properties:
        originalUrl:
          type: string
          format: uri
          example: https://example.com
        expiresAt:
          type: string
          format: date-time
          example: 2025-08-12T12:00:00Z
    LinkResponse:
      type: object
      properties:
        id:
          type: integer
          example: 123
        originalUrl:
          type: string
          format: uri
          example: https://example.com
        shortUrl:
          type: string
          format: uri
          example: http://linktun.com/abc123
        favIcon:
          type: string
          format: uri
          example: https://example.com/favicon.ico
        createdAt:
          type: string
          format: date-time
          example: 2025-08-12T11:00:00Z
        expiresAt:
          type: string
          format: date-time
          example: 2025-08-12T12:00:00Z
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Authenticate a user and return a JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
        "400":
          description: Bad request - Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized - Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /auth/verify:
    get:
      tags:
        - Authentication
      summary: Verify authentication using token in cookies
      description: Validates the JWT token stored in cookies and returns success if valid.
      responses:
        "200":
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Token is valid
        "401":
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
